; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:beermat_rev3]
platform_packages = platformio/framework-arduinoteensy @ symlink://../../framework-arduinoteensy-1.159
platform = teensy @ 5.0.0
lib_extra_dirs = ../../MyLibs
lib_ignore = NativeEthernet, RemoteDisplay
build_flags = -D LV_CONF_PATH="\"ian_lv_conf.h\"". ; for LVGL 9
              ;-D LV_CONF_INCLUDE_SIMPLE            ; For LVGL 8
              -D RDI_DEVELOPMENTS_REV3
              ${common.build_flags}
board_build.f_cpu = 528000000L
monitor_port =  /dev/cu.usbmodem153596401  
board_build.ldscript = linkerScript/RDI_v6_saveITCM_heapSDRAM_setOCRAM_4M_8M_NOCACHE.ld   

[env:teensymm]
platform = https://github.com/platformio/platform-teensy.git
lib_ignore = NativeEthernet, RemoteDisplay
build_flags = ;-D LV_CONF_PATH="\"ian_lv_conf.h\"". ; for LVGL 9
              -D LV_CONF_INCLUDE_SIMPLE             ; For LVGL 8
              ${common.build_flags}
board_build.f_cpu = 528000000L
;monitor_port =  /dev/cu.usbmodem*1 
;board_build.ldscript = linkerScript/imxrt1062_mm_db5_sqlite3.ld
board_build.ldscript = linkerScript/RDI_v6_saveITCM_heapSDRAM_setOCRAM_4M_8M_NOCACHE.ld  
;board_build.ldscript =  linkerScript/db5_sqlite3.ld


[common]
build_unflags = -std=gnu++14
build_flags =
    -std=gnu++17
    -D TEENSY_OPT_FASTER                             ; -O2
    -D SQLITE_OS_OTHER=1
    -D SQLITE_THREADSAFE=0
    -D SQLITE_TEMP_STORE=3
    -D SQLITE_DEFAULT_MMAP_SIZE=0
    -D SQLITE_DEFAULT_MEMSTATUS=0
    -D SQLITE_MAX_EXPR_DEPTH=0
    -D SQLITE_DQS=0
    -D SQLITE_STRICT_SUBTYPE=1
    -D SQLITE_OMIT_DEPRECATED=1
    -D SQLITE_OMIT_SHARED_CACHE=1
    -D SQLITE_OMIT_PROGRESS_CALLBACK=1
    -D SQLITE_OMIT_AUTOINIT=1
    -D SQLITE_OMIT_DECLTYPE=1
    -D SQLITE_OMIT_LOAD_EXTENSION=1
    -D SQLITE_OMIT_UTF16=0
    -D SQLITE_OMIT_WAL=1
    -D USB_SERIAL
    -I config
    -Wl,--print-memory-usage                         ; Linker command to print memory region usage
    -g

[env]
board = teensymm
framework = arduino
monitor_filters = direct                             ; allows color code in serial output
